# Numpy (Ferrari for Mathematical Computing)

#### Numpy (numerical Python) is open source Python libarary that's widely used in science and engineering. the NUmpy library contains multidemensional array data structures, like n dimension arrays, large library of functions, and efficient mathematical operations.


In [35]:
## To import numpy after pip installing call
import numpy as np
eg= np.array([[1,2,3],
                [4,5,6]])
eg.shape

(2, 3)

In [36]:
my_var = np.array([10,30,20.5,15,39,30.4])
my_var

array([10. , 30. , 20.5, 15. , 39. , 30.4])

In [37]:
print(eg)
type(eg)

[[1 2 3]
 [4 5 6]]


numpy.ndarray

# why use numpy?
1. List are slow; Numpy is super fast [Becouse numpy uses fixed type, optimized operations vs Python list are general purpose " hetrogeneous" containers]

2. Numpy uses contiguous Memory vs, List are scattered around (pointrs + Linked list)

3. operations by Element (List do not allow , NUmpy allows)

## Applications of Numpy
#### Mathmetical Operations(scipy is more powerful) , scipy is a collections of Mathmetical algorithms and convenience funtions built on Numpy.

#### Its adds significant power to Python by providing the user with high -  lavel commands and classes for manipulating and visualixing data.
Organised into subpackages like: cluster, constants, differentiate, fft ,  fftpack , integrete, io, linalg,ndimange , odr, optimize, signal, spare, spatial, stats

plotiing(Matplotlib)
Backend (pandas, connect4, digital photography)


In [38]:
list1 = [[1,2,3],[4,5,6],[7,8,9]]
list2 = [[0,1,2],[3,4,5],[6,7,8]]

## this will give error
# list3 = list1* list2
print(list1)
print(list2) 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[0, 1, 2], [3, 4, 5], [6, 7, 8]]


In [39]:
list1 = [1,2,3]
list2 = [4,5,6]

list4 = list1 * 5
list4

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [40]:
## aggregation 

l1 = np.array(list1)
l2 = np.array(list2)
print(f"Adition: {l1+l2}") #element addition
print(f"Multiplication : {l1*l2}") 


Adition: [5 7 9]
Multiplication : [ 4 10 18]


In [41]:
ex_list = [[2,3,4],[0,1,3]]
len(ex_list)

2

In [42]:
len(ex_list[0])

3

In [45]:

import time

start_time = time.perf_counter()

rows_a = len(list1)
cols_a = len(list1[0])
rows_b = len(list2)
cols_b = len(list2[0])

if cols_a != rows_b:
    print ("Invalid matrix dimensons")
else:
    list3 = [[0 for _ in range(cols_b)] for _ in range(rows_a)]
    for row in range(rows_a):
        for col in range(cols_b):
            sum_product =0
            for element in range(cols_a):
                sum_product += list1[row][element] * list2[element][col]
            list3[row][col] =sum_product
    print (list3)

tot_run_time = time.perf_counter() - start_time
print(f"Total elapsed time is : {tot_run_time}")

TypeError: object of type 'int' has no len()